# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = JVIDA_HJRV_controller.o JVIDA_HJRV_main.o JVIDA_HJRV_model.o JVIDA_HJRV_view.o
LINKOBJ  = JVIDA_HJRV_controller.o JVIDA_HJRV_main.o JVIDA_HJRV_model.o JVIDA_HJRV_view.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

JVIDA_HJRV_controller.o: JVIDA_HJRV_controller.c
	$(CPP) -c JVIDA_HJRV_controller.c -o JVIDA_HJRV_controller.o $(CXXFLAGS)

JVIDA_HJRV_main.o: JVIDA_HJRV_main.c
	$(CPP) -c JVIDA_HJRV_main.c -o JVIDA_HJRV_main.o $(CXXFLAGS)

JVIDA_HJRV_model.o: JVIDA_HJRV_model.c
	$(CPP) -c JVIDA_HJRV_model.c -o JVIDA_HJRV_model.o $(CXXFLAGS)

JVIDA_HJRV_view.o: JVIDA_HJRV_view.c
	$(CPP) -c JVIDA_HJRV_view.c -o JVIDA_HJRV_view.o $(CXXFLAGS)
